/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package asm.gd2;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.xml.sax.helpers.NamespaceSupport;

/**
 *
 * @author nguye
 */
public class Vexemphim extends javax.swing.JFrame implements Runnable{

    String ht, loaive, gioxem, gioitinh, ns, sl, tenphim, sdt;
    int giave, tuoi;
    int sol;

    List<Ve> list = new ArrayList<Ve>();
    Ve ve = new Ve();

    public Vexemphim() {

        initComponents();
        Thread t = new Thread(this);
        t.start();
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);

    }

    public void showresult() {
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        for (Ve ve : list) {

            model.addRow(new Object[]{ve.getSoluong(), ve.getHoten(), ve.getGioitinh(), ve.getSdt(), ve.tuoi(), ve.getTenphim(), ve.getGioxem(), ve.getLoaive(), (ve.giave(ve.getLoaive()) + "k")});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        hoten = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt = new javax.swing.JTextArea();
        nam = new javax.swing.JRadioButton();
        nu = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        sodienthoai = new javax.swing.JTextField();
        namsinh = new javax.swing.JTextField();
        soluong = new javax.swing.JTextField();
        cbbtenphim = new javax.swing.JComboBox<>();
        cbbgioxem = new javax.swing.JComboBox<>();
        cbbloaive = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        them = new javax.swing.JButton();
        ghi = new javax.swing.JButton();
        doc = new javax.swing.JButton();
        dongho = new javax.swing.JLabel();
        sua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Họ tên");

        jLabel2.setText("Giới tính");

        jLabel3.setText("Số điện thoại");

        jLabel4.setText("Năm sinh");

        jLabel5.setText("Chọn phim");

        jLabel6.setText("Số lượng vé");

        jLabel7.setText("Giờ xem");

        jLabel8.setText("Loại vé");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Vé Xem Phim");

        hoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotenActionPerformed(evt);
            }
        });

        txt.setColumns(20);
        txt.setRows(5);
        jScrollPane1.setViewportView(txt);

        buttonGroup1.add(nam);
        nam.setText("Nam");

        buttonGroup1.add(nu);
        nu.setText("Nữ");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "số vé", "Họ Tên", "Giới tính", "Số điện thoại", "Tuổi", "Tên phim", "giờ xem", "Loại vé", "Giá vé"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        namsinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namsinhActionPerformed(evt);
            }
        });

        cbbtenphim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "The Duke", "Emergency", "The Northman" }));

        cbbgioxem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1:00", "2:00", "3:00" }));

        cbbloaive.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Học Sinh", "Sinh Viên", "Người đi làm" }));

        jLabel10.setText("Vé");

        them.setText("THÊM");
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });

        ghi.setText("GHI");
        ghi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ghiActionPerformed(evt);
            }
        });

        doc.setText("ĐỌC");
        doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docActionPerformed(evt);
            }
        });

        dongho.setText("jLabel11");

        sua.setText("SỬA");
        sua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suaMouseClicked(evt);
            }
        });
        sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sodienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbbtenphim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbbloaive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbbgioxem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel10))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nam)
                                        .addGap(80, 80, 80)
                                        .addComponent(nu))
                                    .addComponent(hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ghi, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(them, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(doc, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel9)))
                .addGap(60, 355, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dongho)
                .addGap(312, 312, 312))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel9)
                .addGap(2, 2, 2)
                .addComponent(dongho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nam)
                    .addComponent(nu)
                    .addComponent(sua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sodienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(them))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(namsinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbbtenphim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(soluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbbgioxem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cbbloaive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(ghi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doc)))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hotenActionPerformed

    private void themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themActionPerformed
        // TODO add your handling code here:

    
        sdt = sodienthoai.getText();
        ht = hoten.getText();
                ns = namsinh.getText();
        if (ht.equals("")) {

            JOptionPane.showMessageDialog(rootPane, "họ tên k được để trống ");
        }
        if (sdt.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "sdt k được để trống ");
        }
        if (ns.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "năm sinh k được để trống ");
        }
            
        if (Integer.parseInt(ns) > 13) {
            JOptionPane.showMessageDialog(rootPane, "Bạn đủ tuổi xem phim ");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa đủ tuổi :/ ");
        }


         sl = soluong.getText();
        if (Integer.parseInt(sl) <= 0) {
            JOptionPane.showMessageDialog(rootPane, "số lượng vé phải lớn hơn 0 ");
            soluong.setText("");
        } else {

        }

        loaive = cbbloaive.getSelectedItem().toString();
        tenphim = cbbtenphim.getSelectedItem().toString();
        gioxem = cbbgioxem.getSelectedItem().toString();

        sol = Integer.parseInt(soluong.getText());
       tuoi=2022-Integer.parseInt(ns);
        switch (loaive) {
            case "Học Sinh":
                giave = 45;
            case "Sinh Viên":
                giave = 55;
            default:
                giave = 65;
        }

        if (nam.isSelected()) {

            txt.setText("xin chào ông " + ht + " " + tuoi + " tuổi" + " số điện thoại " + sdt + " đã đặt " + sl + " vé xem phim như sau" + "\n");
        }
        if (nu.isSelected()) {

            txt.setText("xin chào bà " + ht + " " + tuoi + " tuổi" + " số điện thoại " + sdt + " đã đặt " + sl + " vé xem phim như sau" + "\n");
        }
        for (int i = 0; i < (Integer.parseInt(sl)); i++) {
            txt.append("vé thứ " + (i + 1) + "\n");
            txt.append("tên phim " + tenphim + "\n");
            txt.append("giờ xem " + gioxem + "\n");
            txt.append("loại vé: " + loaive + "\n");
            txt.append("giá vé: " + giave + "\n");

        }
        txt.append("giá " + sl + " vé là " + (giave * (Integer.parseInt(sl))) + "k");

        String gioitinh;
        if (nam.isSelected()) {
            gioitinh = "Nam";
            ve.setGioitinh(gioitinh);
        } else {
            gioitinh = "Nữ";
            ve.setGioitinh(gioitinh);
        }
        ve.setSoluong(sol);
        ve.setHoten(ht);
        ve.setNamsinh(ns);
        ve.setSdt(sdt);

        ve.setTenphim(tenphim);
        ve.setGioxem(gioxem);
        ve.setLoaive(loaive);
        list.add(ve);


    }//GEN-LAST:event_themActionPerformed
    public void GhiFile() {
        try {
            FileOutputStream ouput = new FileOutputStream("ve.txt");
            ObjectOutputStream oos = new ObjectOutputStream(ouput);

            oos.writeObject(list);

            ouput.close();
            oos.close();
            JOptionPane.showMessageDialog(rootPane, "ghi thành công");
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(rootPane, "ghi k thành công");
        }
    }

    public void DocFile() {
        try {
            FileInputStream fis = new FileInputStream("ve.txt");
            ObjectInputStream ois = new ObjectInputStream(fis);
            list.removeAll(list);
            List<Ve> listve = (List<Ve>) ois.readObject();

            for (Ve ve : listve) {
                list.add(ve);

            }
            showresult();
            fis.close();
            ois.close();
            JOptionPane.showMessageDialog(rootPane, "đọc file ghi thành công");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "đọc file không thành công");
        }
    }
    private void namsinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namsinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namsinhActionPerformed

    private void ghiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ghiActionPerformed
        // TODO add your handling code here:
        GhiFile();
    }//GEN-LAST:event_ghiActionPerformed

    private void docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docActionPerformed
        // TODO add your handling code here:
        DocFile();
    }//GEN-LAST:event_docActionPerformed

    private void suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suaActionPerformed

    private void suaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_suaMouseClicked

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
 
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vexemphim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vexemphim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vexemphim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vexemphim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vexemphim().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbgioxem;
    private javax.swing.JComboBox<String> cbbloaive;
    private javax.swing.JComboBox<String> cbbtenphim;
    private javax.swing.JButton doc;
    private javax.swing.JLabel dongho;
    private javax.swing.JButton ghi;
    private javax.swing.JTextField hoten;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton nam;
    private javax.swing.JTextField namsinh;
    private javax.swing.JRadioButton nu;
    private javax.swing.JTextField sodienthoai;
    private javax.swing.JTextField soluong;
    private javax.swing.JButton sua;
    private javax.swing.JTable table;
    private javax.swing.JButton them;
    private javax.swing.JTextArea txt;
    // End of variables declaration//GEN-END:variables
SimpleDateFormat sdf=new SimpleDateFormat("hh:mm:ss");
    @Override
    public void run() {
        while (true) {            
            Date now= new Date();
            String time= sdf.format(now);
            dongho.setText(time);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(Vexemphim.class.getName()).log(Level.SEVERE, null, ex);
            }
              
            
            
        }
                
          
    
  

       
    }
}
